### ISSUE TITLE
Error NPM I

### ISSUE THREAD

**Issue by daenghunter** [sanzorez/selfsanz#1]
How to install this is script ?

**Comment by sanzorez** [comment]
are you using android?

**Comment by daenghunter** [comment]
@sanzorez i am using rdp windows. How to fix ?

**Comment by sanzorez** [comment]
> @sanzorez i am using rdp windows. How to fix ?

I can use a laptop bro, even windows 7 🙄

**Comment by sanzorez** [comment]
> @sanzorez i am using rdp windows. How to fix ?

have you added the js and ffmpeg nodes paths?, try reinstalling your terminal and if you want to work, use git bash or cygwin
